apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomin-jungdok
  labels:
    app: gomin-jungdok
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gomin-jungdok
  template:
    metadata:
      labels:
        app: gomin-jungdok
    spec:
      containers:
      - name: gomin-jungdok-container
        image: jjwon0407/gomin_jungdok:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3030
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: gomin-jungdok-secret
              key: db-url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: gomin-jungdok-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gomin-jungdok-secret
              key: db-password
        - name: GCS_NAME
          valueFrom:
            secretKeyRef:
              name: gomin-jungdok-secret
              key: gcs-name
        - name: kakao.client
          valueFrom: 
            secretKeyRef: 
              name: gomin-jungdok-secret
              key: kakao-client
        - name: kakao.redirect-uri 
          valueFrom:  
            secretKeyRef:
              name: gomin-jungdok-secret
              key: kakao-redirect-uri
        - name: custom.jwt.secretKey
          valueFrom: 
            secretKeyRef:
              name: gomin-jungdok-secret
              key: custom-jwt-secretKey
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/gcs/gcs.json
        volumeMounts:
        - name: gcs-config-volume
          mountPath: /etc/secrets/gcs
          readOnly: true
        - name: firebase-config-volume
          mountPath: /etc/secrets/firebase
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: gcs-config-volume
        secret:
          secretName: gcs-config
      - name: firebase-config-volume
        secret:
          secretName: firebase-config 

---
apiVersion: v1
kind: Service
metadata:
  name: gomin-jungdok-service
  labels:
    app: gomin-jungdok
spec:
  selector:
    app: gomin-jungdok
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3030