spring.application.name=growcast

server.port=3030
server.address=0.0.0.0

spring.config.import=optional:classpath:.env.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

cloud.gcp.storage.credentials.location=${GCS}
cloud.gcp.storage.bucket=${GCS_NAME}

#테스트용 로그인 계정 생성
spring.security.user.name=user
spring.security.user.password=1234
